modLoader = "javafml"
loaderVersion = "[35,)"
source="https://github.com/samolego/forgified-sgui"
issueTrackerURL = "https://github.com/samolego/forgified-sgui/issues"
license = "LGPL-3.0"

[[mods]]
modId = "sguitest"
version = "${version}"
displayName = "Server GUI lib - TestMod"
authors = "patbox"
contributors="aws404, samo_lego"
description = '''
Library for creating server side guis!
'''
logoFile = "icon.png"

[[dependencies.sguitest]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sguitest]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17.1,)"
ordering = "NONE"
side = "BOTH"
